# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 7e38377
_src_path: gh:scipp/copier_template
description: Build scientific pipelines for your data
max_python: '3.12'
min_python: '3.8'
namespace_package: ''
nightly_deps: ''
orgname: scipp
projectname: sciline
related_projects: Scipp
year: 2023
